#+STARTUP: showeverything

* Set up CI on Travis
* Write tests

* malloc/free : Parameters for accelerators?
We should define qmckl_malloc and qmckl_free just to give the
possibility of the HPC implementations to define how they allocate the
memory (on CPU or GPU, using alternatives to malloc/free, etc).
A possibility could be to pass the id of a NUMA domain as a parameter of
qmckl_malloc, where the domain id is something obtained from the
context.


* TRANSA, TRANSB
* Performance info
* Benchmark interpolation of basis functions
* Complex numbers
* Adjustable number for derivatives (1,2,3)

* Put pictures
* Make the Makefile part of the documented code ?
* Put the data-flow graph in the code.

* Verificarlo TODO
These are installation instructions for
verificarlo which needs to be moved to 
an appropriate place at some point.
** Compilation and Testing

The following steps were required to get
the verificarlo version up and running on
an Ubuntu 20.04 laptop.

1. Compilers
   a. clang - For e.g. clang-7
   b. flang - For e.g. flang-7 : Care needs to be taken
                                 that the flang version 
                                 is compatible with the
                                 clang version used.
                                 There are known issues
                                 with using oneAPI due
                                 to flang being incompatible
                                 with oneAPI supplied clang.
   c. gcc   - For e.g. gcc-7

2. Environment varibales
   a. VFC_BACKENDS - For e.g. `VFC_BACKENDS="libinterflop_ieee.so"` 
