#!/usr/bin/env python3
"""
Generate ctypes function signatures from qmckl.h.

This script parses the QMCkl C header file and generates Python code
with ctypes function signature declarations. It is a development tool
used to keep the Python bindings in sync with the C API.

Usage:
    python generate_bindings.py /path/to/qmckl.h

The output is printed to stdout and can be redirected to a file or
copy-pasted into qmckl/__init__.py.
"""

import re
import sys


def parse_header(header_path):
    """Parse qmckl.h and extract function declarations and error codes."""

    with open(header_path, 'r') as f:
        content = f.read()

    # Extract error codes
    error_pattern = re.compile(
        r'#define\s+(QMCKL_\w+)\s+\(\(qmckl_exit_code\)\s*(\d+)\)'
    )
    errors = error_pattern.findall(content)

    # Remove C comments
    content_no_comments = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
    content_no_comments = re.sub(r'//.*', '', content_no_comments)

    # Extract function declarations (may span multiple lines)
    func_pattern = re.compile(
        r'(qmckl_exit_code|qmckl_context|const\s+char\s*\*|void)\s*\n?\s*'
        r'(qmckl_\w+)\s*\(([^)]*)\)\s*;',
        re.MULTILINE
    )
    functions = []
    for match in func_pattern.finditer(content_no_comments):
        ret_type = match.group(1).strip()
        func_name = match.group(2).strip()
        params_str = match.group(3).strip()

        params = []
        if params_str and params_str != 'void':
            raw_params = [p.strip() for p in params_str.split(',')]
            for p in raw_params:
                params.append(parse_param(p))

        functions.append({
            'return_type': ret_type,
            'name': func_name,
            'params': params,
        })

    return errors, functions


def parse_param(param_str):
    """Parse a single C parameter declaration into type and name."""
    param_str = param_str.strip()

    is_const = 'const' in param_str
    clean = param_str.replace('const', '').strip()
    is_pointer = '*' in clean

    clean = clean.replace('*', ' ').split()
    if len(clean) >= 2:
        c_type = clean[0]
        name = clean[-1]
    elif len(clean) == 1:
        c_type = clean[0]
        name = ''
    else:
        c_type = param_str
        name = ''

    return {
        'c_type': c_type,
        'name': name,
        'is_pointer': is_pointer,
        'is_const': is_const,
        'raw': param_str,
    }


CTYPES_MAP = {
    'qmckl_context': 'qmckl_context',
    'qmckl_exit_code': 'qmckl_exit_code',
    'int64_t': 'ctypes.c_int64',
    'int32_t': 'ctypes.c_int32',
    'double': 'ctypes.c_double',
    'float': 'ctypes.c_float',
    'char': 'ctypes.c_char',
    'int': 'ctypes.c_int32',
    'bool': 'ctypes.c_bool',
}

RETURN_MAP = {
    'qmckl_exit_code': 'qmckl_exit_code',
    'qmckl_context': 'qmckl_context',
    'void': 'None',
    'const char *': 'ctypes.c_char_p',
    'const char*': 'ctypes.c_char_p',
}


def param_to_ctypes(param):
    """Convert a parsed parameter to its ctypes representation."""
    c_type = param['c_type']
    is_pointer = param['is_pointer']

    if c_type == 'char' and is_pointer:
        return 'ctypes.c_char_p'

    base = CTYPES_MAP.get(c_type, f'ctypes.c_{c_type}')

    if is_pointer:
        return f'ctypes.POINTER({base})'
    return base


def generate_signatures(errors, functions):
    """Generate Python code with ctypes function signatures."""

    lines = []
    lines.append("# Auto-generated ctypes function signatures")
    lines.append("# Generated by generate_bindings.py")
    lines.append("")

    lines.append("# Error codes")
    for name, value in errors:
        padding = ' ' * max(1, 30 - len(name))
        lines.append(f"{name}{padding}= {value}")
    lines.append("")

    lines.append("# Function signatures")
    lines.append("")
    for func in functions:
        ret_type = func['return_type']
        name = func['name']
        params = func['params']

        lines.append(f"# {ret_type} {name}({', '.join(p['raw'] for p in params)});")

        argtypes = [param_to_ctypes(p) for p in params]
        if argtypes:
            if len(argtypes) <= 3:
                lines.append(f"_lib.{name}.argtypes = [{', '.join(argtypes)}]")
            else:
                lines.append(f"_lib.{name}.argtypes = [")
                for i, at in enumerate(argtypes):
                    comma = ',' if i < len(argtypes) - 1 else ''
                    lines.append(f"    {at}{comma}")
                lines.append("]")
        else:
            lines.append(f"_lib.{name}.argtypes = []")

        restype = RETURN_MAP.get(ret_type, CTYPES_MAP.get(ret_type, f'ctypes.c_{ret_type}'))
        lines.append(f"_lib.{name}.restype  = {restype}")
        lines.append("")

    return '\n'.join(lines)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <path/to/qmckl.h>", file=sys.stderr)
        sys.exit(1)

    header_path = sys.argv[1]
    errors, functions = parse_header(header_path)

    print(f"# Found {len(errors)} error codes and {len(functions)} functions",
          file=sys.stderr)
    print(generate_signatures(errors, functions))


if __name__ == '__main__':
    main()
